# 多元线性回归

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [3]:
boston = datasets.load_boston()

X = boston.data
y = boston.target

X = X[y < 50.0]
y = y[y < 50.0]

In [4]:
X.shape

(490, 13)

In [5]:
from playML.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, seed = 666)

In [10]:
from playML.LinearRegression import LinearRegression

In [11]:
reg = LinearRegression()

In [12]:
reg.fit_normal(X_train, y_train)

LinearRegression()

In [13]:
reg.coef_

array([-1.18919477e-01,  3.63991462e-02, -3.56494193e-02,  5.66737830e-02,
       -1.16195486e+01,  3.42022185e+00, -2.31470282e-02, -1.19509560e+00,
        2.59339091e-01, -1.40112724e-02, -8.36521175e-01,  7.92283639e-03,
       -3.81966137e-01])

In [14]:
reg.interception_

34.16143549623827

In [15]:
reg.score(X_test, y_test)

0.81298026026586

## scikit-learn中的回归问题

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
boston = datasets.load_boston()

X = boston.data
y = boston.target

X = X[y < 50.0]
y = y[y < 50.0]

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state =666 )

## scikit-learn中的线性回归

In [19]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()

In [20]:
lin_reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [21]:
lin_reg.coef_

array([-1.14235739e-01,  3.12783163e-02, -4.30926281e-02, -9.16425531e-02,
       -1.09940036e+01,  3.49155727e+00, -1.40778005e-02, -1.06270960e+00,
        2.45307516e-01, -1.23179738e-02, -8.80618320e-01,  8.43243544e-03,
       -3.99667727e-01])

In [22]:
lin_reg.score(X_test, y_test)

0.8008916199519077

### kNN Regressor

In [23]:
from sklearn.neighbors import KNeighborsRegressor

In [24]:
knn_reg = KNeighborsRegressor()

In [25]:
knn_reg.fit(X_train, y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=5, p=2,
          weights='uniform')

In [26]:
knn_reg.score(X_train, y_train)

0.7008057422390714

In [27]:
from sklearn.model_selection import GridSearchCV

param_grid = [
    {
        'weights': ['uniform'],
        'n_neighbors': [i for i in range(1, 11)]
    },
    {
        'weights': ['distance'],
        'n_neighbors': [i for i in range(1,11)],
        'p': [i for i in range(1, 6)]
    }
]

In [28]:
knn_reg = KNeighborsRegressor()
grid_search = GridSearchCV(knn_reg,param_grid,n_jobs = -1)
grid_search.fit(X_train,y_train)

GridSearchCV(cv=None, error_score='raise',
       estimator=KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=5, p=2,
          weights='uniform'),
       fit_params=None, iid=True, n_jobs=-1,
       param_grid=[{'weights': ['uniform'], 'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}, {'weights': ['distance'], 'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'p': [1, 2, 3, 4, 5]}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [29]:
grid_search.best_params_

{'n_neighbors': 6, 'p': 1, 'weights': 'distance'}

In [30]:
grid_search.best_score_

0.6060327991735741

In [31]:
grid_search.best_estimator_.score(X_test, y_test)

0.7354244906092771

## 更多关于线性回归模型的讨论

In [32]:
boston = datasets.load_boston()

X = boston.data
y = boston.target

X = X[y < 50.0]
y = y[y < 50.0]

In [35]:
from sklearn.linear_model import LinearRegression

In [36]:
lin_reg = LinearRegression()

In [37]:
lin_reg.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [38]:
lin_reg.coef_

array([-1.05574295e-01,  3.52748549e-02, -4.35179251e-02,  4.55405227e-01,
       -1.24268073e+01,  3.75411229e+00, -2.36116881e-02, -1.21088069e+00,
        2.50740082e-01, -1.37702943e-02, -8.38888137e-01,  7.93577159e-03,
       -3.50952134e-01])

In [39]:
np.argsort(lin_reg.coef_)

array([ 4,  7, 10, 12,  0,  2,  6,  9, 11,  1,  8,  3,  5], dtype=int64)

In [40]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [41]:
boston.feature_names[np.argsort(lin_reg.coef_)]

array(['NOX', 'DIS', 'PTRATIO', 'LSTAT', 'CRIM', 'INDUS', 'AGE', 'TAX',
       'B', 'ZN', 'RAD', 'CHAS', 'RM'], dtype='<U7')

## 线性回归算法总结

### 典型的参数学习
### 只能解决回归问题
### 很多分类方法中，线性回归是基础（如逻辑回归）
### 而kNN即可以解决分类问题，又可以解决回归问题

### 对数据有假设：线性。 而knn对数据没有假设

### 线性回归最大的优点是对数据具有强解释性

## 多元线性回归
### 多元线性回归的正规方程解(Normal Equation)

#  $$\theta = (X^T_bX_b)^{-1}X^T_by$$

# $\theta$ = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y_train)