In [8]:
from sklearn import datasets
import matplotlib.pyplot as plt
import numpy as np

In [9]:
iris = datasets.load_iris()

In [10]:
X = iris.data
y = iris.target

In [11]:
X.shape

(150, 4)

In [12]:
y.shape

(150,)

## train_test_split

In [13]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [19]:
shuffle_indexes = np.random.permutation(len(X))
shuffle_indexes

array([ 22,  51,  50, 137,   7,  98, 120,  48, 122,  46,  87,  11,  10,
        58, 111, 139,  30, 118,   6,  70, 116,  66, 119, 105,  44,   0,
        72, 100, 127, 125, 117, 123,   1,  88,  41,  69,  35, 144, 103,
        57,  91,  95,  23,  76,  13, 101,  16,   8, 124, 108,  78, 135,
        15, 132,  54,  26, 148,  82, 142, 141, 146,  39,  64,  18,  17,
        34,  73,  45,  97, 106,  37, 130,  42, 113,  55,  38, 128,   5,
       134,  56,  99,  67,  71,  59, 145,  47, 104, 133,  81, 121,  86,
        80,  33,  89,  27, 138,   2,  90,  31, 147,  96,  83,  75,  85,
        92, 112,  62,  63,  24, 110,  77,  93,  53, 129, 149,  68, 143,
        25,  28,   9,  29,  21,  52,  19,  74, 109,  84, 115,  49, 140,
       114, 107,  43,  79,  12,  65, 102, 136,  61,  36, 126,   3,  14,
        20,  60,  32,   4, 131,  94,  40])

In [16]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [17]:
test_size

30

In [20]:
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [21]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [22]:
X_train.shape

(120, 4)

In [23]:
from playML.model_selection import train_test_split

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [26]:
from sklearn.neighbors import KNeighborsClassifier

In [28]:
my_knn_clf = KNeighborsClassifier(n_neighbors = 3)

In [29]:
my_knn_clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [30]:
y_predict = my_knn_clf.predict(X_test)

In [31]:
y_predict

array([1, 2, 0, 2, 0, 2, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 2, 2, 0,
       1, 2, 1, 0, 1, 2, 0, 1])

In [32]:
y_test

array([1, 2, 0, 2, 0, 2, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 2, 2, 0,
       1, 2, 1, 0, 1, 2, 0, 1])

In [33]:
sum(y_predict == y_test)

30

In [34]:
sum(y_predict == y_test) / len(y_test)

1.0

## sklearn 中的train_test_split

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 666)

In [37]:
X_train.shape

(120, 4)