In [1]:
import numpy as np
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X[:10,:]#观看前十行

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target)

### scikit-learn中的StandardScaler

In [7]:
from sklearn.preprocessing import StandardScaler 

In [8]:
standardscaler = StandardScaler()

In [9]:
standardscaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [10]:
standardscaler.mean_

array([5.85      , 3.02232143, 3.83392857, 1.24107143])

In [11]:
standardscaler.scale_

array([0.83953644, 0.41612795, 1.7442535 , 0.75847045])

In [13]:
standardscaler.transform(X_train)

array([[-0.41689674, -1.2551943 ,  0.0952106 ,  0.07769396],
       [ 0.65512344,  0.42698063,  0.84051511,  1.39613689],
       [-1.25069021, -0.05364078, -1.39539841, -1.24074897],
       [-0.89335015,  1.14791274, -1.39539841, -1.24074897],
       [ 0.17867003, -0.29395149,  0.38186618,  0.34138254],
       [ 1.0124635 ,  0.18666992,  1.01250846,  1.52798118],
       [-0.17867003, -0.29395149,  0.20987284,  0.07769396],
       [ 0.53601009, -0.7745729 ,  0.61119065,  0.73691542],
       [ 0.65512344, -0.7745729 ,  0.84051511,  0.86875971],
       [ 0.77423679, -0.05364078,  1.12717069,  1.26429259],
       [ 0.65512344,  0.42698063,  0.38186618,  0.34138254],
       [-1.0124635 ,  0.42698063, -1.51006065, -1.37259326],
       [-0.29778338, -0.53426219,  0.61119065,  1.00060401],
       [ 0.05955668, -0.05364078,  0.20987284,  0.34138254],
       [-0.89335015,  1.14791274, -1.39539841, -1.37259326],
       [-1.25069021,  0.90760204, -1.28073618, -1.37259326],
       [ 2.44182374,  1.

In [14]:
X_train =standardscaler.transform(X_train)
X_train

array([[-0.41689674, -1.2551943 ,  0.0952106 ,  0.07769396],
       [ 0.65512344,  0.42698063,  0.84051511,  1.39613689],
       [-1.25069021, -0.05364078, -1.39539841, -1.24074897],
       [-0.89335015,  1.14791274, -1.39539841, -1.24074897],
       [ 0.17867003, -0.29395149,  0.38186618,  0.34138254],
       [ 1.0124635 ,  0.18666992,  1.01250846,  1.52798118],
       [-0.17867003, -0.29395149,  0.20987284,  0.07769396],
       [ 0.53601009, -0.7745729 ,  0.61119065,  0.73691542],
       [ 0.65512344, -0.7745729 ,  0.84051511,  0.86875971],
       [ 0.77423679, -0.05364078,  1.12717069,  1.26429259],
       [ 0.65512344,  0.42698063,  0.38186618,  0.34138254],
       [-1.0124635 ,  0.42698063, -1.51006065, -1.37259326],
       [-0.29778338, -0.53426219,  0.61119065,  1.00060401],
       [ 0.05955668, -0.05364078,  0.20987284,  0.34138254],
       [-0.89335015,  1.14791274, -1.39539841, -1.37259326],
       [-1.25069021,  0.90760204, -1.28073618, -1.37259326],
       [ 2.44182374,  1.

In [16]:
x_test_standard = standardscaler.transform(x_test)

In [17]:
from sklearn.neighbors import KNeighborsClassifier

In [18]:
knn_clf = KNeighborsClassifier(n_neighbors = 3)

In [19]:
knn_clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [20]:
knn_clf.score(x_test_standard,y_test)

0.9473684210526315