# numpy.array基础

In [1]:
import numpy

In [2]:
import numpy as np

In [3]:
np.__version__ ##查询版本

'1.16.3'

 ## Python LIst的特点

In [10]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
L [5]

5

In [12]:
L [5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [13]:
L [5] = "Machine Learning"

In [14]:
L

[0, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

In [15]:
import array

In [17]:
arr = array.array('i', [i for i in range(10)])

In [18]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr[5]

5

In [20]:
arr[5] = "Machine Learning"

TypeError: an integer is required (got type str)

## numpy.array

In [21]:
nparr = np .array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
nparr[5]

5

In [23]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [24]:
nparr.dtype

dtype('int32')

In [25]:
nparr2 = np.array([1, 2, 3.0])

In [27]:
nparr2.dtype

dtype('float64')

## 其他创建 numpp.array 的方法

In [28]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
np.zeros(shape(3,5), dtype = int)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
np.ones((3,5),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [34]:
np.full((3,5), 666) #第一个参数为shape，第二个参数为value+-

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [37]:
np.full(fill_value = 666,shape = (3,5))

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

## arange

In [39]:
[i for i in range(0,20,2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [40]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [41]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### linspace

In [43]:
np.linspace(0, 20, 10)#在0和20之间截出十个等距点，包含0和20

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [44]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random

In [45]:
np.random.randint(0, 10,10)

array([1, 2, 4, 7, 2, 0, 1, 4, 7, 9])

In [46]:
np.random.randint(0,1,10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [47]:
np.random.randint(4,8,size=10)

array([5, 5, 6, 6, 5, 4, 5, 4, 6, 7])

In [49]:
np.random.randint(4, 8, size = (3, 5))

array([[4, 4, 7, 5, 6],
       [6, 4, 5, 7, 5],
       [4, 7, 5, 6, 5]])

In [50]:
np.random.seed(666)

In [51]:
np.random.randint(4, 8, size = (3, 5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [52]:
np.random.seed(666)
np.random.randint(4, 8, size = (3, 5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [53]:
np.random.random()

0.2811684913927954

In [54]:
np.random.random(10)

array([0.46284169, 0.23340091, 0.76706421, 0.81995656, 0.39747625,
       0.31644109, 0.15551206, 0.73460987, 0.73159555, 0.8578588 ])

In [55]:
np.random.random((3,5))

array([[0.76741234, 0.95323137, 0.29097383, 0.84778197, 0.3497619 ],
       [0.92389692, 0.29489453, 0.52438061, 0.94253896, 0.07473949],
       [0.27646251, 0.4675855 , 0.31581532, 0.39016259, 0.26832981]])

In [56]:
 np.random.normal()

0.7760516793129695

In [57]:
np.random.normal(10,100)

128.06359754812632

In [58]:
np.random.normal(0,1,size = (3,5)## 均值为0方差为1的随机3*5的随机矩阵

array([[ 0.06102404,  1.07856138, -0.79783572,  1.1701326 ,  0.1121217 ],
       [ 0.03185388, -0.19206285,  0.78611284, -1.69046314, -0.98873907],
       [ 0.31398563,  0.39638567,  0.57656584, -0.07019407,  0.91250436]])

In [59]:
np.random? #查询api

In [60]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap

### numpy.array的基本操作

In [61]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
X = np.arange(15).reshape(3,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 基本属性

In [63]:
x.ndim ##查询是几维数组

1

In [64]:
X.ndim

2

In [65]:
x.shape #查询元祖

(10,)

In [66]:
X.shape

(3, 5)

In [67]:
x.size

10

In [68]:
X.size

15

### numpy.array的数据访问

In [69]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
x[0]

0

In [71]:
x[-1]

9

In [72]:
X[0][0]

0

In [73]:
X[1][-1]

9

In [74]:
X[(2, 2)]

12

In [75]:
x[0:5] ##访问0到5（不包含5）

array([0, 1, 2, 3, 4])

In [76]:
x[5:]

array([5, 6, 7, 8, 9])

In [77]:
x[::2]##第三个参数为步长

array([0, 2, 4, 6, 8])

In [78]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [79]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [80]:
X[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [81]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [82]:
X[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [83]:
X[:2,::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [84]:
X[::-1,::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [86]:
X[0,:]

array([0, 1, 2, 3, 4])

In [87]:
subX = X[:2,:3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [88]:
subX[0,0]=100

In [89]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [97]:
X[0,0] = 0

In [98]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [99]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [111]:
subx = X[:2,:3].copy()
subx

array([[0, 1, 2],
       [5, 6, 7]])

In [112]:
subx[0,0] = 100

In [113]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Reshape

In [114]:
x.shape

(10,)

In [115]:
x.ndim

1

In [117]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [118]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
A = x.reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [120]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
B = x.reshape(1,10)

In [122]:
B.ndim

2

In [123]:
B.shape

(1, 10)

In [124]:
x.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [125]:
x.reshape(10,-1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])